/*
 * @Author: 呲牙
 * @LastEditors: 呲牙
 * @Date: 2022-04-13 10:34:15
 * @LastEditTime: 2022-04-13 10:34:15
 * @Email: 1340482172@qq.com
 * @FilePath: \bootstrapc:\Users\13404\Downloads\bootstrap-3.4.1-dist\bootstrap-3.4.1-dist\js\npm.js
 * @Environment: Win 10 Python 3.8
 * @Description: 
 */
// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')